//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimatorStateMachineWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AnimatorStateMachine), typeof(UnityEngine.StateMachineBehaviour));
		L.RegFunction("OnStateEnter", OnStateEnter);
		L.RegFunction("OnStateMachineEnter", OnStateMachineEnter);
		L.RegFunction("OnStateExit", OnStateExit);
		L.RegFunction("OnStateMachineExit", OnStateMachineExit);
		L.RegFunction("New", _CreateAnimatorStateMachine);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("onEnterStateCallBack", get_onEnterStateCallBack, set_onEnterStateCallBack);
		L.RegVar("onEnterStateMachineCallBack", get_onEnterStateMachineCallBack, set_onEnterStateMachineCallBack);
		L.RegVar("onExitStateCallBack", get_onExitStateCallBack, set_onExitStateCallBack);
		L.RegVar("onExitStateMachineCallBack", get_onExitStateMachineCallBack, set_onExitStateMachineCallBack);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAnimatorStateMachine(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AnimatorStateMachine obj = new AnimatorStateMachine();
				ToLua.Push(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AnimatorStateMachine.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStateEnter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				UnityEngine.AnimatorStateInfo arg1 = StackTraits<UnityEngine.AnimatorStateInfo>.Check(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				obj.OnStateEnter(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				UnityEngine.AnimatorStateInfo arg1 = StackTraits<UnityEngine.AnimatorStateInfo>.Check(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				UnityEngine.Animations.AnimatorControllerPlayable arg3 = StackTraits<UnityEngine.Animations.AnimatorControllerPlayable>.Check(L, 5);
				obj.OnStateEnter(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AnimatorStateMachine.OnStateEnter");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStateMachineEnter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.OnStateMachineEnter(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				UnityEngine.Animations.AnimatorControllerPlayable arg2 = StackTraits<UnityEngine.Animations.AnimatorControllerPlayable>.Check(L, 4);
				obj.OnStateMachineEnter(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AnimatorStateMachine.OnStateMachineEnter");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStateExit(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				UnityEngine.AnimatorStateInfo arg1 = StackTraits<UnityEngine.AnimatorStateInfo>.Check(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				obj.OnStateExit(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				UnityEngine.AnimatorStateInfo arg1 = StackTraits<UnityEngine.AnimatorStateInfo>.Check(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				UnityEngine.Animations.AnimatorControllerPlayable arg3 = StackTraits<UnityEngine.Animations.AnimatorControllerPlayable>.Check(L, 5);
				obj.OnStateExit(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AnimatorStateMachine.OnStateExit");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStateMachineExit(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.OnStateMachineExit(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				AnimatorStateMachine obj = (AnimatorStateMachine)ToLua.CheckObject<AnimatorStateMachine>(L, 1);
				UnityEngine.Animator arg0 = (UnityEngine.Animator)ToLua.CheckObject<UnityEngine.Animator>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				UnityEngine.Animations.AnimatorControllerPlayable arg2 = StackTraits<UnityEngine.Animations.AnimatorControllerPlayable>.Check(L, 4);
				obj.OnStateMachineExit(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AnimatorStateMachine.OnStateMachineExit");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onEnterStateCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<UnityEngine.AnimatorStateInfo> ret = obj.onEnterStateCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onEnterStateCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onEnterStateMachineCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<int> ret = obj.onEnterStateMachineCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onEnterStateMachineCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onExitStateCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<UnityEngine.AnimatorStateInfo> ret = obj.onExitStateCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onExitStateCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onExitStateMachineCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<int> ret = obj.onExitStateMachineCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onExitStateMachineCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onEnterStateCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<UnityEngine.AnimatorStateInfo> arg0 = (System.Action<UnityEngine.AnimatorStateInfo>)ToLua.CheckDelegate<System.Action<UnityEngine.AnimatorStateInfo>>(L, 2);
			obj.onEnterStateCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onEnterStateCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onEnterStateMachineCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<int> arg0 = (System.Action<int>)ToLua.CheckDelegate<System.Action<int>>(L, 2);
			obj.onEnterStateMachineCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onEnterStateMachineCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onExitStateCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<UnityEngine.AnimatorStateInfo> arg0 = (System.Action<UnityEngine.AnimatorStateInfo>)ToLua.CheckDelegate<System.Action<UnityEngine.AnimatorStateInfo>>(L, 2);
			obj.onExitStateCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onExitStateCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onExitStateMachineCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimatorStateMachine obj = (AnimatorStateMachine)o;
			System.Action<int> arg0 = (System.Action<int>)ToLua.CheckDelegate<System.Action<int>>(L, 2);
			obj.onExitStateMachineCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onExitStateMachineCallBack on a nil value");
		}
	}
}

