//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_EventObjectWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.EventObject), typeof(DragonBones.BaseObject));
		L.RegFunction("ActionDataToInstance", ActionDataToInstance);
		L.RegFunction("New", _CreateDragonBones_EventObject);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("START", get_START, null);
		L.RegVar("LOOP_COMPLETE", get_LOOP_COMPLETE, null);
		L.RegVar("COMPLETE", get_COMPLETE, null);
		L.RegVar("FADE_IN", get_FADE_IN, null);
		L.RegVar("FADE_IN_COMPLETE", get_FADE_IN_COMPLETE, null);
		L.RegVar("FADE_OUT", get_FADE_OUT, null);
		L.RegVar("FADE_OUT_COMPLETE", get_FADE_OUT_COMPLETE, null);
		L.RegVar("FRAME_EVENT", get_FRAME_EVENT, null);
		L.RegVar("SOUND_EVENT", get_SOUND_EVENT, null);
		L.RegVar("time", get_time, set_time);
		L.RegVar("type", get_type, set_type);
		L.RegVar("name", get_name, set_name);
		L.RegVar("armature", get_armature, set_armature);
		L.RegVar("bone", get_bone, set_bone);
		L.RegVar("slot", get_slot, set_slot);
		L.RegVar("animationState", get_animationState, set_animationState);
		L.RegVar("actionData", get_actionData, set_actionData);
		L.RegVar("data", get_data, set_data);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDragonBones_EventObject(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DragonBones.EventObject obj = new DragonBones.EventObject();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DragonBones.EventObject.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ActionDataToInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			DragonBones.ActionData arg0 = (DragonBones.ActionData)ToLua.CheckObject<DragonBones.ActionData>(L, 1);
			DragonBones.EventObject arg1 = (DragonBones.EventObject)ToLua.CheckObject<DragonBones.EventObject>(L, 2);
			DragonBones.Armature arg2 = (DragonBones.Armature)ToLua.CheckObject<DragonBones.Armature>(L, 3);
			DragonBones.EventObject.ActionDataToInstance(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_START(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.START);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LOOP_COMPLETE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.LOOP_COMPLETE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_COMPLETE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.COMPLETE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FADE_IN(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.FADE_IN);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FADE_IN_COMPLETE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.FADE_IN_COMPLETE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FADE_OUT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.FADE_OUT);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FADE_OUT_COMPLETE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.FADE_OUT_COMPLETE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FRAME_EVENT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.FRAME_EVENT);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SOUND_EVENT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.EventObject.SOUND_EVENT);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_time(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			float ret = obj.time;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index time on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			string ret = obj.type;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index type on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_armature(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Armature ret = obj.armature;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index armature on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Bone ret = obj.bone;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bone on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_slot(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Slot ret = obj.slot;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index slot on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_animationState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.AnimationState ret = obj.animationState;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_actionData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.ActionData ret = obj.actionData;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index actionData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.UserData ret = obj.data;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_time(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.time = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index time on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.type = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index type on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_armature(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Armature arg0 = (DragonBones.Armature)ToLua.CheckObject<DragonBones.Armature>(L, 2);
			obj.armature = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index armature on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Bone arg0 = (DragonBones.Bone)ToLua.CheckObject<DragonBones.Bone>(L, 2);
			obj.bone = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bone on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_slot(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.Slot arg0 = (DragonBones.Slot)ToLua.CheckObject<DragonBones.Slot>(L, 2);
			obj.slot = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index slot on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_animationState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.AnimationState arg0 = (DragonBones.AnimationState)ToLua.CheckObject<DragonBones.AnimationState>(L, 2);
			obj.animationState = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_actionData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.ActionData arg0 = (DragonBones.ActionData)ToLua.CheckObject<DragonBones.ActionData>(L, 2);
			obj.actionData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index actionData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.EventObject obj = (DragonBones.EventObject)o;
			DragonBones.UserData arg0 = (DragonBones.UserData)ToLua.CheckObject<DragonBones.UserData>(L, 2);
			obj.data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}
}

