//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Listener_HttpApiRequest_ResponseDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Listener<HttpApiRequest,ResponseData>), typeof(System.Object), "Listener_HttpApiRequest_ResponseData");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Callback", Callback);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Listener<HttpApiRequest,ResponseData> obj = (Listener<HttpApiRequest,ResponseData>)ToLua.CheckObject<Listener<HttpApiRequest,ResponseData>>(L, 1);
			System.Action<HttpApiRequest,ResponseData> arg0 = (System.Action<HttpApiRequest,ResponseData>)ToLua.CheckDelegate<System.Action<HttpApiRequest,ResponseData>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Listener<HttpApiRequest,ResponseData> obj = (Listener<HttpApiRequest,ResponseData>)ToLua.CheckObject<Listener<HttpApiRequest,ResponseData>>(L, 1);
			System.Action<HttpApiRequest,ResponseData> arg0 = (System.Action<HttpApiRequest,ResponseData>)ToLua.CheckDelegate<System.Action<HttpApiRequest,ResponseData>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Callback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Listener<HttpApiRequest,ResponseData> obj = (Listener<HttpApiRequest,ResponseData>)ToLua.CheckObject<Listener<HttpApiRequest,ResponseData>>(L, 1);
			HttpApiRequest arg0 = (HttpApiRequest)ToLua.CheckObject<HttpApiRequest>(L, 2);
			ResponseData arg1 = (ResponseData)ToLua.CheckObject<ResponseData>(L, 3);
			obj.Callback(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

