//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MahjongResultDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MahjongResultData), typeof(System.Object));
		L.RegFunction("New", _CreateMahjongResultData);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("key", get_key, set_key);
		L.RegVar("list", get_list, set_list);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMahjongResultData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MahjongResultData obj = new MahjongResultData();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MahjongResultData.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_key(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MahjongResultData obj = (MahjongResultData)o;
			int ret = obj.key;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index key on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_list(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MahjongResultData obj = (MahjongResultData)o;
			MahjongTingData[] ret = obj.list;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index list on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_key(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MahjongResultData obj = (MahjongResultData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.key = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index key on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_list(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MahjongResultData obj = (MahjongResultData)o;
			MahjongTingData[] arg0 = ToLua.CheckObjectArray<MahjongTingData>(L, 2);
			obj.list = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index list on a nil value");
		}
	}
}

