//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MahjongRuleTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MahjongRuleType), typeof(System.Object));
		L.RegFunction("New", _CreateMahjongRuleType);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("DuiDuiHu", 1);
		L.RegConstant("ZhongZhang", 2);
		L.RegConstant("MengQing", 3);
		L.RegConstant("JinGouDiao", 4);
		L.RegConstant("YaoJiu", 5);
		L.RegConstant("JiangDui", 6);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMahjongRuleType(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MahjongRuleType obj = new MahjongRuleType();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MahjongRuleType.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

