//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ResponseCodeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ResponseCode), typeof(System.Object));
		L.RegFunction("New", _CreateResponseCode);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("SUCCESS", 0);
		L.RegConstant("FAILED", 1);
		L.RegConstant("TIMEOUT", 2);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateResponseCode(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ResponseCode obj = new ResponseCode();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ResponseCode.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

