//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TSingleton_PlaybackDataManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TSingleton<PlaybackDataManager>), typeof(System.Object), "TSingleton_PlaybackDataManager");
		L.RegFunction("New", _CreateTSingleton_PlaybackDataManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("EmptyTypes", get_EmptyTypes, null);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTSingleton_PlaybackDataManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TSingleton<PlaybackDataManager> obj = new TSingleton<PlaybackDataManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TSingleton<PlaybackDataManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmptyTypes(IntPtr L)
	{
		try
		{
			ToLua.Push(L, TSingleton<PlaybackDataManager>.EmptyTypes);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, TSingleton<PlaybackDataManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

