//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_RenderingPathWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.RenderingPath));
		L.RegVar("UsePlayerSettings", get_UsePlayerSettings, null);
		L.RegVar("VertexLit", get_VertexLit, null);
		L.RegVar("Forward", get_Forward, null);
		L.RegVar("DeferredLighting", get_DeferredLighting, null);
		L.RegVar("DeferredShading", get_DeferredShading, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.RenderingPath>.Check = CheckType;
		StackTraits<UnityEngine.RenderingPath>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.RenderingPath arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.RenderingPath), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UsePlayerSettings(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderingPath.UsePlayerSettings);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VertexLit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderingPath.VertexLit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Forward(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderingPath.Forward);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DeferredLighting(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderingPath.DeferredLighting);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DeferredShading(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderingPath.DeferredShading);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.RenderingPath o = (UnityEngine.RenderingPath)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

