//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WwwLoadTaskWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WwwLoadTask), typeof(Listener<ResponseData>));
		L.RegFunction("SetTimeout", SetTimeout);
		L.RegFunction("Run", Run);
		L.RegFunction("Stop", Stop);
		L.RegFunction("New", _CreateWwwLoadTask);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWwwLoadTask(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				WwwLoadTask obj = new WwwLoadTask(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
				WwwLoadTask obj = new WwwLoadTask(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WwwLoadTask.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTimeout(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WwwLoadTask obj = (WwwLoadTask)ToLua.CheckObject<WwwLoadTask>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetTimeout(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Run(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WwwLoadTask obj = (WwwLoadTask)ToLua.CheckObject<WwwLoadTask>(L, 1);
			obj.Run();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Stop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WwwLoadTask obj = (WwwLoadTask)ToLua.CheckObject<WwwLoadTask>(L, 1);
			obj.Stop();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

