
--面板，大厅的普通面板都使用层数4，设置6为loading，7为Wating，8为Toast，9为Alert
--isSpecial是否为特殊面板，即统一关闭的时候不处理
--isDestroy是否关闭时销毁
--isUnloadAsset是否销毁时卸载Prefab资源
--isRequire是否require,否则dofile
PanelConfig = {
    --通用
    Alert = { path = ScriptPath.ViewCommon, bundleName = BundleName.Common, assetName = "AlertPanel", layer = 9, isSpecial = true },
    NewAlert = { path = ScriptPath.ViewCommon, bundleName = BundleName.Common, assetName = "NewAlertPanel", layer = 9, isSpecial = true },
    Toast = { path = ScriptPath.ViewCommon, bundleName = BundleName.Common, assetName = "ToastPanel", layer = 8, isSpecial = true },
    Waiting = { path = ScriptPath.ViewCommon, bundleName = BundleName.Common, assetName = "WaitingPanel", layer = 7, isSpecial = true },
    Mask = { path = ScriptPath.ViewCommon, bundleName = BundleName.Common, assetName = "MaskPanel", layer = 7, isSpecial = true },
    --登录
    Login = { path = ScriptPath.View, bundleName = BundleName.Login, assetName = "LoginPanel", layer = 1, isSpecial = true },
    PhoneLogin = { path = ScriptPath.View, bundleName = BundleName.Login, assetName = "PhoneLoginPanel", layer = 4 },
    PhoneRegister = { path = ScriptPath.View, bundleName = BundleName.Login, assetName = "PhoneRegisterPanel", layer = 4 },
    --大厅
    Shopping = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ShoppingPanel", layer = 4 },
    Lobby = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbyPanel", layer = 1, isDestroy = true },
    UpdateNotice = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "UpdateNoticePanel", layer = 5, isDestroy = true },
    LobbyMacth = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbyMatchPanel", layer = 2, isSpecial = true },
    Notice = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "NoticePanel", layer = 4 },
    LobbyNotice = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbyNoticePanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    Activity = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ActivityPanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    JoinRoom = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "JoinRoomPanel", layer = 4 },
    BindPhone = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "BindPhonePanel", layer = 4, isDestroy = true, isUnloadAsset = true, isRequire = true },
    PwdModify = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "PwdModifyPanel", layer = 4, isDestroy = true, isUnloadAsset = true, isRequire = true },
    ShengMing = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ShengMingPanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    RealName = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "RealNamePanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    Setup = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "SetupPanel", layer = 4 },
    LobbyShare = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbySharePanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    HelpNotice = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "HelpNoticePanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    Record = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "RecordPanel", layer = 5, isSpecial = true },
    RecordSearch = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "RecordSearchPanel", layer = 5 },
    RecordSub = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "RecordSubPanel", layer = 5, isSpecial = true },
    UserInfo = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "UserInfoPanel", layer = 4 },
    ModifyHeadIcon = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ModifyHeadIconPanel", layer = 4 },
    InviteCode = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "InviteCodePanel", layer = 4 },

    HeadFrameModify = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "HeadFrameModifyPanel", layer = 4 },
    LobbyMatchRule = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbyMatchRulePanel", layer = 3 },
    LobbyMatchTips = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LobbyMatchTipsPanel", layer = 3 },
    Mall = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "MallPanel", layer = 4 },
    Service = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ServicePanel", layer = 4 },
    Agent = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "AgentPanel", layer = 4 },
    Email = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "EmailPanel", layer = 4, isDestroy = true },
    GetReward = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "GetRewardsPanel", layer = 4, isDestroy = true },
    GoldMatch = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "GoldMatchPanel", layer = 5 },
    Protocal = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "ProtocalPanel", layer = 3, isDestroy = true, isUnloadAsset = true },
    CheckIn = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "CheckInPanel", layer = 4, isDestroy = true, isUnloadAsset = true, isRequire = true },
    LuckyWheel = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "LuckyWheelPanel", layer = 3, isDestroy = true, isUnloadAsset = true },
    TaskSystem = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "TaskSystemPanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    Trumpet = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "TrumpetPanel", layer = 4, isDestroy = true },
    WheelTip = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "WheelTipPanel", layer = 4 },
    Upgrade = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "UpgradePanel", layer = 4, isDestroy = true, isUnloadAsset = true },
    MoreGame = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "MoreGamesPanel", layer = 4 },
    Message = { path = ScriptPath.View, bundleName = BundleName.Panel, assetName = "MessagePanel", layer = 4 },
    --
    --
    --创建房间相关面板
    CreateRoom = { path = ScriptPath.ViewCreateRoom, bundleName = BundleName.Panel, assetName = "CreateRoomPanel", layer = 5 },
    ModifyRoom = { path = ScriptPath.ViewCreateRoom, bundleName = BundleName.Panel, assetName = "ModifyRoomPanel", layer = 5 },
    CreateGobangRoom = { path = ScriptPath.ViewCreateRoom, bundleName = BundleName.Panel, assetName = "CreateGobangRoomPanel", layer = 4 },
    CreateRoomAdvanced = { path = ScriptPath.ViewCreateRoom, bundleName = BundleName.Panel, assetName = "CreateRoomAdvancedPanel", layer = 5 },
    --
    --
    --房间相关面板
    RoomGps = { path = ScriptPath.ViewRoom, bundleName = BundleName.Room, assetName = "RoomGpsPanel", layer = 5 },
    RoomGps5 = { path = ScriptPath.ViewRoom, bundleName = BundleName.Room, assetName = "RoomGps5Panel", layer = 5 },
    RoomSpeech = { path = ScriptPath.ViewRoom, bundleName = BundleName.Room, assetName = "RoomSpeechPanel", layer = 4 },
    RoomChat = { path = ScriptPath.ViewRoom, bundleName = BundleName.Room, assetName = "RoomChatPanel", layer = 4, isDestroy = true },
    RoomUserInfo = { path = ScriptPath.ViewRoom, bundleName = BundleName.Room, assetName = "RoomUserInfoPanel", layer = 4, isDestroy = true, isRequire = true },

    ----------------------------------------联盟----------------------------------------------------------------------------------------------------------------
    UnionEnter = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionEnterPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionJoin = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionJoinPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionRoom = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionRoomPanel", layer = 4 },
    UnionLuckyValueManage = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionLuckyValueManagePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionPersonalData = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPersonalDataPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionScoreManager = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionScoreManagerPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPartnerPercentChange = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerPercentChangePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionPartnerPercentAndScoreChangePanel = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerPercentAndScoreChangePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionMyCard = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionMyCardPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionSuperiorCard = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSuperiorCardPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionPartner = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionLowerPartner = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionLowerPartnerPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionLowerMember = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionLowerMemberPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionSetting = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSettingPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionStyle = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionStylePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionInputNumber = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionInputNumberPanel", layer = 6, isDestroy = true, isRequire = true },
    UnionFollowPlayer = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionFollowPlayerPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionRule = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionRulePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionNotice = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionNoticePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionCreate = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionCreatePanel", layer = 4, isDestroy = true, isRequire = true },
    UnionSetScore = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSetScorePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionSetScoreNotice = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSetScoreNoticePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionScoreChange = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionScoreChangePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPartnerMoreAction = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerMoreActionPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionSetRatio = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSetRatioPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionSetKeepBase = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSetKeepBasePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionKeepBasePop = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionKeepBasePopPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionKeepBaseDetail = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionKeepBaseDetailPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPlayerLayer = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPlayerLayerPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionDarkRoom = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionDarkRoomPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionDarkRoomGroup = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionDarkRoomGroupPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionDarkRoomAdd = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionDarkRoomAddPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionWarnScore = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionWarnScorePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPartnerChange = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerChangePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionMemberChange = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionMemberChangePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionFaceRecord = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionFaceRecordPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPartnerMgr = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPartnerMgrPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionTeamDetails = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionTeamDetailsPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionGameRecord = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionGameRecordPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionRoomDetails = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionRoomDetailsPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionDeskDetails = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionDeskDetailsPanel", layer = 4, isDestroy = true, isRequire = true },
    UnionSetPartner = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionSetPartnerPanel", layer = 5, isDestroy = true, isRequire = true },
    UnionInvitePlayerNotice = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionInvitePlayerNoticePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionPlayableGame = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionPlayableGamePanel", layer = 5, isDestroy = true, isRequire = true },
    UnionScoreSet = { path = ScriptPath.ViewUnion, bundleName = BundleName.Union, assetName = "UnionScoreSetPanel", layer = 5, isDestroy = true, isRequire = true },
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}